site_name: DTM ID
nav:
  - Home: index.md
  - "Frontend Developer":
    - JavaScript: index.md
    - Angular:
      - Component: 
        - "Mengenal Component": doc_angular/components/intro-component.md
        - "Blok Component": doc_angular/components/blok-pembangun-component.md
        - "Properti Penting Metadata": doc_angular/components/properti-penting-metadata.md
      - "Data Binding":
        - "Mengenal Data Binding": doc_angular/data-binding/intro.md
theme:
  name: material
